### ISSUE TITLE
Error: Unable to resolve module ./EncryptedFiles

### ISSUE THREAD

**Issue by Jaerker** [emeraldsanto/react-native-encrypted-storage#103]
Hi! So I'm not sure what is happening here, tried to check the code and it all seems legit. 

However when i try to import EncryptedStorage, like so: 
import EncryptedStorage from 'react-native-encrypted-storage';

and then uses it like this: 

 setToken = async() => {
        try {

             await EncryptedStorage.setItem("Value", JSON.stringify({
                name:'johan',
                token:'test',
                username:'test',
            }));

        } catch (e) {
            console.log(e);
        }
    }
(this code is inside a store context, hence the lack of const)

I get this message when running app: 

<pre><span style="background-color:#C01C28"><font color="#300A24"><b> BUNDLE </b></font></span><font color="#AAAAAA"> ./</font><b>index.js</b> 

<font color="#C01C28">error</font>: Error: Unable to resolve module ./EncryptedStorage from /home/johan/webdev/react-native/testApp/node_modules/react-native-encrypted-storage/src/index.ts: 

None of these files exist:
  * node_modules/react-native-encrypted-storage/src/EncryptedStorage(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules/react-native-encrypted-storage/src/EncryptedStorage/index(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
<font color="#C01C28"><b>&gt;</b></font><font color="#5E5C64"> 1 |</font> <font color="#2AA1B3">export</font> { <font color="#2AA1B3">default</font> } <font color="#2AA1B3">from</font> <font color="#26A269">&apos;./EncryptedStorage&apos;</font><font color="#A2734C">;</font>
 <font color="#5E5C64">   |</font>                          <font color="#C01C28"><b>^</b></font>
 <font color="#5E5C64"> 2 |</font>
    at ModuleResolver.resolveDependency (/home/johan/webdev/react-native/testApp/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:152:15)
    at DependencyGraph.resolveDependency (/home/johan/webdev/react-native/testApp/node_modules/metro/src/node-haste/DependencyGraph.js:264:43)
    at Object.resolve (/home/johan/webdev/react-native/testApp/node_modules/metro/src/lib/transformHelpers.js:170:21)
    at resolveDependencies (/home/johan/webdev/react-native/testApp/node_modules/metro/src/DeltaBundler/graphOperations.js:466:33)
    at processModule (/home/johan/webdev/react-native/testApp/node_modules/metro/src/DeltaBundler/graphOperations.js:232:31)
    at async addDependency (/home/johan/webdev/react-native/testApp/node_modules/metro/src/DeltaBundler/graphOperations.js:361:18)
    at async Promise.all (index 0)
    at async processModule (/home/johan/webdev/react-native/testApp/node_modules/metro/src/DeltaBundler/graphOperations.js:279:3)
    at async traverseDependenciesForSingleFile (/home/johan/webdev/react-native/testApp/node_modules/metro/src/DeltaBundler/graphOperations.js:221:3)
    at async traverseDependencies (/home/johan/webdev/react-native/testApp/node_modules/metro/src/DeltaBundler/graphOperations.js:147:7)

</pre>

Now, I have no idea why. Tried it outside of the storeContext, my coding knowledge is not that experienced yet to understand what I'm actually doing wrong. Would love if someone could help me here :)

**Comment by Jaerker** [comment]
so sorry, for some reason it wanted a reboot (which feels odd on a Ubuntu computer) and I was too stupid to even try..
