### ISSUE TITLE
RNEncryptedStorageModule.java:26 error on Play Store release

### ISSUE THREAD

**Issue by AdrianBordeianu** [emeraldsanto/react-native-encrypted-storage#32]
FATAL EXCEPTION: create_react_context
java.lang.NoClassDefFoundError: android.security.keystore.KeyGenParameterSpec$Builder
	at androidx.security.crypto.MasterKeys.createAES256GCMKeyGenParameterSpec(MasterKeys.java:72)
	at androidx.security.crypto.MasterKeys.<clinit>(MasterKeys.java:55)
	at com.emeraldsanto.encryptedstorage.RNEncryptedStorageModule.<init>(RNEncryptedStorageModule.java:26)
	at com.emeraldsanto.encryptedstorage.RNEncryptedStoragePackage.createNativeModules(RNEncryptedStoragePackage.java:15)
	at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
	at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
	at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1347)
	at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1318)
	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1225)
	at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131)
	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1016)
	at java.lang.Thread.run(Thread.java:841)

**Device specifications**
Model name
Galaxy S3
Android version (SDK)
Android 4.3 (SDK 18)
Screen size
720 x 1280

**Comment by firstfloordigital** [comment]
encountering the same issue, @AdrianBordeianu  did you find a fix?

**Comment by emeraldsanto** [comment]
That sounds like an issue with Proguard not including the required classes in your builds.

In guessing this is only happening using release APK/AAB?

**Comment by AdrianBordeianu** [comment]
@firstfloordigital I didn't find a fix yet, I was thinking about migrating to react-native-keychain, but there are some release build issues as well.

@emeraldsanto release APK/AAB it's the only way I tried for that device, because it was found during Firebase Automatic tests that Google runs before a release. Do you have any suggestion of how to handle this?

**Comment by emeraldsanto** [comment]
I see now you're running on a device using API 18, the minimum requirement for using the AndroidX security library, which is used by this package, is API 23. That's what's causing the issue.

**Comment by AdrianBordeianu** [comment]
Those tests are ran automatically at PlayStore release, I cannot control them, the target API for the package is already set to 23.

**Comment by AdrianBordeianu** [comment]
I'll try to set minSdk for the project to 23 and will come back with an update.

Thank you very much for now.
